@baseUrl = http://localhost:3000
@userId = 6a4ce00c2322ccbe8f1498fd

### TEST API
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
    "name": "Jane Doe Update"

}


### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}
